export interface HasuraTableDefinition {
  name: string;
  columns: string[];
}

export const PUBLIC_TABLES: HasuraTableDefinition[] = [
  {
    name: 'data_updates',
    columns: [
      'id',
      'block_height',
      'block_timestamp',
      'receipt_id',
      'operation',
      'author',
      'partition_id',
      'path',
      'value',
      'value_json',
      'account_id',
      'data_type',
      'data_id',
      'app_relpath',
      'group_id',
      'group_path',
      'is_group_content',
      'target_account',
      'parent_path',
      'parent_author',
      'parent_type',
      'ref_path',
      'ref_author',
      'ref_type',
      'refs',
      'ref_authors',
      'derived_id',
      'derived_type',
      'writes',
      'extra_data',
      'reaction_kind',
      'channel',
      'kind',
      'audiences',
      'actor_id',
      'payer_id',
    ],
  },
  {
    name: 'storage_updates',
    columns: [
      'id',
      'block_height',
      'block_timestamp',
      'receipt_id',
      'operation',
      'author',
      'partition_id',
      'amount',
      'previous_balance',
      'new_balance',
      'pool_id',
      'pool_key',
      'group_id',
      'reason',
      'actor_id',
      'payer_id',
      'target_id',
      'available_balance',
      'donor',
      'payer',
      'previous_pool_balance',
      'new_pool_balance',
      'bytes',
      'remaining_allowance',
      'pool_account',
      'max_bytes',
      'new_shared_bytes',
      'new_used_bytes',
      'pool_available_bytes',
      'used_bytes',
      'extra_data',
    ],
  },
  {
    name: 'group_updates',
    columns: [
      'id',
      'block_height',
      'block_timestamp',
      'receipt_id',
      'operation',
      'author',
      'partition_id',
      'group_id',
      'member_id',
      'member_nonce',
      'member_nonce_path',
      'role',
      'level',
      'path',
      'value',
      'pool_key',
      'amount',
      'previous_pool_balance',
      'new_pool_balance',
      'quota_bytes',
      'quota_used',
      'daily_limit',
      'previously_enabled',
      'proposal_id',
      'proposal_type',
      'status',
      'sequence_number',
      'title',
      'description',
      'auto_vote',
      'created_at',
      'locked_member_count',
      'locked_deposit',
      'expires_at',
      'tally_path',
      'counter_path',
      'voter',
      'approve',
      'total_votes',
      'yes_votes',
      'no_votes',
      'should_execute',
      'should_reject',
      'voted_at',
      'voting_period',
      'participation_quorum',
      'approval_threshold',
      'permission_key',
      'permission_value',
      'permission_target',
      'name',
      'is_public',
      'creator_role',
      'storage_allocation',
      'extra_data',
    ],
  },
  {
    name: 'permission_updates',
    columns: [
      'id',
      'block_height',
      'block_timestamp',
      'receipt_id',
      'operation',
      'author',
      'partition_id',
      'path',
      'target_id',
      'public_key',
      'level',
      'expires_at',
      'value',
      'deleted',
      'derived_id',
      'derived_type',
      'permission_nonce',
    ],
  },
  {
    name: 'contract_updates',
    columns: [
      'id',
      'block_height',
      'block_timestamp',
      'receipt_id',
      'operation',
      'author',
      'partition_id',
      'path',
      'derived_id',
      'derived_type',
      'target_id',
      'actor_id',
      'payer_id',
      'extra_data',
    ],
  },
  {
    name: 'profiles_current',
    columns: [
      'account_id',
      'field',
      'value',
      'block_height',
      'block_timestamp',
      'operation',
    ],
  },
  {
    name: 'pages_current',
    columns: [
      'account_id',
      'data_id',
      'value',
      'block_height',
      'block_timestamp',
      'operation',
    ],
  },
  {
    name: 'apps_current',
    columns: [
      'path',
      'account_id',
      'data_id',
      'app_relpath',
      'value',
      'value_json',
      'operation',
      'block_height',
      'block_timestamp',
      'receipt_id',
      'author',
      'actor_id',
    ],
  },
  {
    name: 'profile_search',
    columns: [
      'account_id',
      'name',
      'bio',
      'avatar',
      'banner',
      'kind',
      'industry',
      'open_jobs_count',
      'standing_count',
      'standing_with_count',
      'mutual_standing_count',
      'endorsements_received_count',
      'endorsements_given_count',
      'first_profile_timestamp',
      'last_profile_block',
      'last_profile_timestamp',
      'last_activity_block',
      'search_text',
    ],
  },
  {
    name: 'profile_discover',
    columns: [
      'account_id',
      'name',
      'bio',
      'avatar',
      'banner',
      'kind',
      'industry',
      'open_jobs_count',
      'standing_count',
      'standing_with_count',
      'mutual_standing_count',
      'endorsements_received_count',
      'endorsements_given_count',
      'first_profile_timestamp',
      'last_profile_block',
      'last_profile_timestamp',
      'last_activity_block',
      'search_text',
      'reputation',
      'confidence_score',
      'discover_score',
    ],
  },
  {
    name: 'jobs_current',
    columns: [
      'account_id',
      'job_id',
      'path',
      'value',
      'value_json',
      'block_height',
      'block_timestamp',
      'operation',
    ],
  },
  {
    name: 'jobs_search',
    columns: [
      'org_account_id',
      'job_id',
      'path',
      'title',
      'description',
      'url',
      'ends',
      'since',
      'org_name',
      'org_kind',
      'org_industry',
      'org_avatar',
      'search_text',
      'block_height',
      'block_timestamp',
    ],
  },
  {
    name: 'posts_current',
    columns: [
      'account_id',
      'post_id',
      'value',
      'block_height',
      'block_timestamp',
      'receipt_id',
      'parent_path',
      'parent_author',
      'parent_type',
      'ref_path',
      'ref_author',
      'ref_type',
      'channel',
      'kind',
      'audiences',
      'group_id',
      'is_group_content',
      'root_path',
      'root_author',
    ],
  },
  {
    name: 'posts_feed',
    columns: [
      'account_id',
      'post_id',
      'value',
      'block_height',
      'block_timestamp',
      'receipt_id',
      'parent_path',
      'parent_author',
      'parent_type',
      'ref_path',
      'ref_author',
      'ref_type',
      'channel',
      'kind',
      'audiences',
      'group_id',
      'is_group_content',
      'author_name',
      'author_avatar',
      'group_name',
      'amplify_heat',
      'root_path',
      'root_author',
    ],
  },
  {
    name: 'post_amplify_heat',
    columns: ['post_path', 'heat'],
  },
  {
    name: 'standings_current',
    columns: [
      'account_id',
      'target_account',
      'value',
      'block_height',
      'block_timestamp',
    ],
  },
  {
    name: 'blocks_current',
    columns: [
      'account_id',
      'target_account',
      'value',
      'block_height',
      'block_timestamp',
    ],
  },
  {
    name: 'mutual_standings_current',
    columns: [
      'account_id',
      'mutual_account',
      'value',
      'block_height',
      'block_timestamp',
    ],
  },
  {
    name: 'groups_current',
    columns: [
      'group_id',
      'owner_id',
      'group_name',
      'group_description',
      'group_banner_cid',
      'group_badge_cid',
      'is_public',
      'is_member_driven',
      'group_topics',
      'creator_role',
      'storage_allocation',
      'block_height',
      'block_timestamp',
      'operation',
    ],
  },
  {
    name: 'group_members_current',
    columns: [
      'group_id',
      'member_id',
      'role',
      'level',
      'is_owner',
      'is_admin',
      'can_moderate',
      'group_name',
      'group_description',
      'group_banner_cid',
      'group_badge_cid',
      'is_public',
      'is_member_driven',
      'group_topics',
      'block_height',
      'block_timestamp',
    ],
  },
  {
    name: 'group_member_counts',
    columns: ['group_id', 'member_count'],
  },
  {
    name: 'groups_by_member_count',
    columns: [
      'group_id',
      'owner_id',
      'group_name',
      'is_public',
      'creator_role',
      'storage_allocation',
      'block_height',
      'block_timestamp',
      'operation',
      'group_description',
      'group_banner_cid',
      'group_badge_cid',
      'is_member_driven',
      'group_topics',
      'member_count',
    ],
  },
  {
    name: 'group_blacklist_current',
    columns: [
      'group_id',
      'member_id',
      'block_height',
      'block_timestamp',
      'group_name',
      'is_public',
      'is_member_driven',
    ],
  },
  {
    name: 'reactions_current',
    columns: [
      'account_id',
      'post_owner',
      'reaction_kind',
      'path',
      'value',
      'block_height',
      'block_timestamp',
      'operation',
    ],
  },
  {
    name: 'reaction_counts',
    columns: [
      'post_owner',
      'reaction_kind',
      'post_path',
      'reaction_count',
      'last_reaction_block',
    ],
  },
  {
    name: 'scarce_album_love_fans',
    columns: ['post_owner', 'collection_id', 'fan_count', 'last_love_block'],
  },
  {
    name: 'scarce_album_love_fan_ids',
    columns: [
      'post_owner',
      'collection_id',
      'fan_account_ids',
      'fan_count',
      'last_love_block',
    ],
  },
  {
    name: 'scarce_drop_love_fans',
    columns: ['post_owner', 'collection_id', 'fan_count', 'last_love_block'],
  },
  {
    name: 'scarce_drop_love_fan_ids',
    columns: [
      'post_owner',
      'collection_id',
      'fan_account_ids',
      'fan_count',
      'last_love_block',
    ],
  },
  {
    name: 'scarce_collection_love_fans',
    columns: ['post_owner', 'collection_id', 'fan_count', 'last_love_block'],
  },
  {
    name: 'scarce_collection_love_fan_ids',
    columns: [
      'post_owner',
      'collection_id',
      'fan_account_ids',
      'fan_count',
      'last_love_block',
    ],
  },
  {
    name: 'standing_counts',
    columns: ['account_id', 'standing_with_count', 'last_standing_block'],
  },
  {
    name: 'standing_out_counts',
    columns: [
      'account_id',
      'standing_with_others_count',
      'last_standing_block',
    ],
  },
  {
    name: 'thread_replies',
    columns: [
      'reply_author',
      'reply_id',
      'parent_author',
      'parent_path',
      'parent_type',
      'value',
      'block_height',
      'block_timestamp',
      'group_id',
      'root_path',
      'root_author',
    ],
  },
  {
    name: 'quotes',
    columns: [
      'quote_author',
      'quote_id',
      'ref_author',
      'ref_path',
      'ref_type',
      'value',
      'block_height',
      'block_timestamp',
      'group_id',
    ],
  },
  {
    name: 'reposts',
    columns: [
      'repost_author',
      'repost_id',
      'ref_author',
      'ref_path',
      'ref_type',
      'value',
      'block_height',
      'block_timestamp',
      'group_id',
    ],
  },
  {
    name: 'thread_reply_counts',
    columns: [
      'parent_author',
      'parent_path',
      'reply_count',
      'last_reply_block',
    ],
  },
  {
    name: 'quote_counts',
    columns: ['ref_author', 'ref_path', 'quote_count', 'last_quote_block'],
  },
  {
    name: 'repost_counts',
    columns: ['ref_author', 'ref_path', 'repost_count', 'last_repost_block'],
  },
  {
    name: 'edges_current',
    columns: [
      'edge_id',
      'source_account',
      'target_account',
      'target_type',
      'target_path',
      'edge_kind',
      'source',
      'target',
      'edge_type',
      'value',
      'block_height',
      'block_timestamp',
      'operation',
      'group_id',
    ],
  },
  {
    name: 'edge_counts',
    columns: [
      'account_id',
      'target_type',
      'edge_type',
      'edge_kind',
      'inbound_count',
      'last_block',
    ],
  },
  {
    name: 'claims_current',
    columns: [
      'issuer',
      'subject',
      'claim_type',
      'claim_id',
      'path',
      'value',
      'block_height',
      'block_timestamp',
      'operation',
    ],
  },
  {
    name: 'saves_current',
    columns: [
      'account_id',
      'content_path',
      'value',
      'block_height',
      'block_timestamp',
      'operation',
    ],
  },
  {
    name: 'endorsements_current',
    columns: [
      'issuer',
      'target',
      'topic_or_target',
      'path',
      'value',
      'block_height',
      'block_timestamp',
      'operation',
    ],
  },
  {
    name: 'saves_current',
    columns: [
      'account_id',
      'content_path',
      'value',
      'block_height',
      'block_timestamp',
      'operation',
    ],
  },
  {
    name: 'endorsements_current',
    columns: [
      'issuer',
      'target',
      'topic_or_target',
      'path',
      'value',
      'block_height',
      'block_timestamp',
      'operation',
    ],
  },
  {
    name: 'post_hashtags',
    columns: [
      'account_id',
      'post_id',
      'hashtag',
      'block_height',
      'block_timestamp',
      'group_id',
      'heat',
    ],
  },
  {
    name: 'hashtag_counts',
    columns: ['hashtag', 'post_count', 'last_block'],
  },
  {
    name: 'post_tickers',
    columns: [
      'account_id',
      'post_id',
      'ticker',
      'block_height',
      'block_timestamp',
      'group_id',
      'heat',
    ],
  },
  {
    name: 'ticker_counts',
    columns: ['ticker', 'post_count', 'last_block'],
  },
  {
    name: 'post_places',
    columns: [
      'account_id',
      'post_id',
      'place',
      'block_height',
      'block_timestamp',
      'group_id',
      'heat',
    ],
  },
  {
    name: 'place_counts',
    columns: ['place', 'post_count', 'last_block'],
  },
  {
    name: 'profile_hashtags',
    columns: ['account_id', 'hashtag', 'block_height', 'block_timestamp'],
  },
  {
    name: 'profile_tags',
    columns: ['account_id', 'tag', 'block_height', 'block_timestamp'],
  },
  {
    name: 'profile_tag_counts',
    columns: ['tag', 'profile_count', 'last_block'],
  },
  {
    name: 'profile_tickers',
    columns: ['account_id', 'ticker', 'block_height', 'block_timestamp'],
  },
  {
    name: 'profile_mentions',
    columns: [
      'account_id',
      'mentioned_account_id',
      'block_height',
      'block_timestamp',
    ],
  },
  {
    name: 'token_events',
    columns: [
      'id',
      'block_height',
      'block_timestamp',
      'receipt_id',
      'event_type',
      'owner_id',
      'amount',
      'memo',
      'old_owner_id',
      'new_owner_id',
      'extra_data',
    ],
  },
  {
    name: 'token_balances',
    columns: [
      'account_id',
      'last_event_type',
      'last_event_block',
      'updated_at',
    ],
  },
  {
    name: 'boost_events',
    columns: [
      'id',
      'block_height',
      'block_timestamp',
      'receipt_id',
      'account_id',
      'event_type',
      'success',
      'amount',
      'effective_boost',
      'months',
      'new_months',
      'new_effective_boost',
      'elapsed_ns',
      'total_released',
      'remaining_pool',
      'infra_share',
      'rewards_share',
      'total_pool',
      'receiver_id',
      'old_owner',
      'new_owner',
      'old_version',
      'new_version',
      'deposit',
      'extra_data',
    ],
  },
  {
    name: 'booster_state',
    columns: [
      'account_id',
      'locked_amount',
      'effective_boost',
      'lock_months',
      'total_claimed',
      'total_credits_purchased',
      'last_event_type',
      'last_event_block',
      'updated_at',
    ],
  },
  {
    name: 'boost_credit_purchases',
    columns: [
      'id',
      'block_height',
      'block_timestamp',
      'receipt_id',
      'account_id',
      'amount',
      'infra_share',
      'rewards_share',
    ],
  },
  {
    name: 'rewards_events',
    columns: [
      'id',
      'block_height',
      'block_timestamp',
      'receipt_id',
      'account_id',
      'event_type',
      'success',
      'amount',
      'source',
      'credited_by',
      'app_id',
      'new_balance',
      'old_owner',
      'new_owner',
      'old_max',
      'new_max',
      'caller',
      'old_version',
      'new_version',
      'extra_data',
    ],
  },
  {
    name: 'user_reward_state',
    columns: [
      'account_id',
      'total_earned',
      'total_claimed',
      'last_credit_block',
      'last_claim_block',
      'updated_at',
    ],
  },
  {
    name: 'scarces_events',
    columns: [
      'id',
      'block_height',
      'block_timestamp',
      'receipt_id',
      'event_type',
      'operation',
      'author',
      'token_id',
      'collection_id',
      'listing_id',
      'owner_id',
      'creator_id',
      'buyer_id',
      'seller_id',
      'bidder',
      'winner_id',
      'sender_id',
      'receiver_id',
      'account_id',
      'contract_id',
      'scarce_contract_id',
      'amount',
      'price',
      'old_price',
      'new_price',
      'bid_amount',
      'attempted_price',
      'marketplace_fee',
      'app_pool_amount',
      'app_commission',
      'creator_payment',
      'revenue',
      'new_balance',
      'initial_balance',
      'refunded_amount',
      'refund_per_token',
      'refund_pool',
      'quantity',
      'total_supply',
      'redeem_count',
      'max_redeems',
      'bid_count',
      'refundable_count',
      'reserve_price',
      'buy_now_price',
      'min_bid_increment',
      'winning_bid',
      'expires_at',
      'auction_duration_ns',
      'anti_snipe_extension_ns',
      'app_id',
      'funder',
      'old_owner',
      'new_owner',
      'old_recipient',
      'new_recipient',
      'reason',
      'mode',
      'memo',
      'token_ids',
      'prices',
      'receivers',
      'accounts',
      'old_version',
      'new_version',
      'total_fee_bps',
      'app_pool_fee_bps',
      'platform_storage_fee_bps',
      'start_time',
      'end_time',
      'new_expires_at',
      'old_expires_at',
      'approval_id',
      'deposit',
      'remaining_balance',
      'cap',
      'extra_data',
    ],
  },
  {
    name: 'scarces_active_listings',
    columns: [
      'listing_key',
      'kind',
      'listing_id',
      'token_id',
      'seller_id',
      'creator_id',
      'app_id',
      'price',
      'price_numeric',
      'reserve_price',
      'buy_now_price',
      'highest_bid',
      'bid_count',
      'copies',
      'remaining',
      'minted_count',
      'expires_at',
      'title',
      'media',
      'source_post_path',
      'card_bg',
      'extra_json',
      'medium_kind',
      'audio_format',
      'facets',
      'listed_block_height',
      'listed_block_timestamp',
      'updated_block_height',
      'updated_block_timestamp',
    ],
  },
  {
    name: 'scarces_collections_current',
    columns: [
      'collection_id',
      'creator_id',
      'app_id',
      'price',
      'allowlist_price',
      'total_supply',
      'minted_count',
      'remaining',
      'start_time',
      'end_time',
      'created_at',
      'mint_mode',
      'max_per_wallet',
      'paused',
      'cancelled',
      'banned',
      'transferable',
      'renewable',
      'max_redeems',
      'random_assignment',
      'app_commission_bps',
      'title',
      'media',
      'description',
      'kind',
      'medium_kind',
      'source_post_path',
      'metadata_template',
      'metadata',
      'extra_json',
      'royalty_json',
      'created_block_height',
      'created_block_timestamp',
      'updated_block_height',
      'updated_block_timestamp',
    ],
  },
  {
    name: 'scarces_apps',
    columns: [
      'app_id',
      'owner_id',
      'primary_sale_bps',
      'creator_access',
      'curated',
      'metadata',
      'created_block_height',
      'created_block_timestamp',
      'updated_block_height',
      'updated_block_timestamp',
    ],
  },
  {
    name: 'scarces_app_creators',
    columns: [
      'id',
      'app_id',
      'account_id',
      'role',
      'added_block_height',
      'added_block_timestamp',
    ],
  },
  {
    name: 'scarces_token_owners',
    columns: [
      'token_id',
      'owner_id',
      'burned',
      'collection_id',
      'app_id',
      'minted_block_timestamp',
      'updated_block_timestamp',
    ],
  },
  {
    name: 'scarces_app_stats',
    columns: [
      'app_id',
      'drops_total',
      'minted_total',
      'unique_holders',
      'sales_count',
      'sales_volume',
      'live_listings',
      'last_activity_timestamp',
    ],
  },
  {
    name: 'scarces_app_stats_hot',
    columns: [
      'app_id',
      'drops_total',
      'minted_total',
      'unique_holders',
      'sales_count',
      'sales_volume',
      'live_listings',
      'last_activity_timestamp',
    ],
  },
  {
    name: 'scarces_collections_trade_stats',
    columns: [
      'collection_id',
      'app_id',
      'sales_count',
      'sales_volume',
      'last_sale_timestamp',
    ],
  },
  {
    name: 'scarces_active_offers',
    columns: [
      'offer_key',
      'kind',
      'token_id',
      'collection_id',
      'buyer_id',
      'amount',
      'expires_at',
      'created_block_height',
      'created_block_timestamp',
      'updated_block_height',
      'updated_block_timestamp',
    ],
  },
  {
    name: 'social_spend_events',
    columns: [
      'id',
      'block_height',
      'block_timestamp',
      'receipt_id',
      'account_id',
      'event_type',
      'success',
      'spender_id',
      'amount',
      'app_id',
      'action',
      'target_type',
      'target_id',
      'season_id',
      'tag',
      'recipient_id',
      'treasury_amount',
      'season_amount',
      'target_amount',
      'metadata',
      'label',
      'active',
      'starts_at_ns',
      'ends_at_ns',
      'claim_starts_at_ns',
      'root',
      'total_amount',
      'paused',
      'old_treasury_id',
      'treasury_id',
      'settlement_publisher',
      'owner_id',
      'old_version',
      'new_version',
      'extra_data',
    ],
  },
  {
    name: 'leaderboard_boost',
    columns: [
      'account_id',
      'locked_amount',
      'effective_boost',
      'lock_months',
      'total_claimed',
      'total_credits_purchased',
      'last_event_block',
      'rank',
    ],
  },
  {
    name: 'leaderboard_rewards',
    columns: [
      'account_id',
      'total_earned',
      'total_claimed',
      'unclaimed',
      'credit_count',
      'last_credit_block',
      'last_claim_block',
      'rank',
    ],
  },
  {
    name: 'reward_activity_daily',
    columns: [
      'account_id',
      'activity_date',
      'credit_count',
      'total_amount',
      'last_block',
    ],
  },
  {
    name: 'content_activity',
    columns: [
      'account_id',
      'total_posts',
      'reply_count',
      'quote_count',
      'group_posts',
      'total_reactions_received',
      'avg_reactions_per_post',
      'active_days',
      'unique_reply_targets',
      'last_post_block',
    ],
  },
  {
    name: 'scarces_activity',
    columns: [
      'account_id',
      'items_created',
      'items_sold',
      'revenue_earned',
      'items_purchased',
      'amount_spent',
      'collections_created',
      'last_scarces_block',
    ],
  },
  {
    name: 'reputation_scores',
    columns: [
      'account_id',
      'standing_with',
      'standing_out',
      'mutual_standing',
      'endorsements_received',
      'paid_support_social',
      'paid_support_events',
      'paid_support_spenders',
      'unique_inbound_peers',
      'replies_received',
      'quotes_received',
      'unique_scarce_fans',
      'amplify_points',
      'amplify_social',
      'amplify_events',
      'boost',
      'lock_months',
      'rewards_earned',
      'total_posts',
      'reply_count',
      'reactions_received',
      'avg_reactions',
      'active_days',
      'unique_conversations',
      'scarces_created',
      'scarces_sold',
      'scarces_revenue_near',
      'social_score',
      'commitment_score',
      'quality_score',
      'consistency_score',
      'scarces_score',
      'reputation',
      'confidence_score',
      'rank',
    ],
  },
  {
    name: 'leaderboard_by_app',
    columns: [
      'app_id',
      'account_id',
      'action_count',
      'total_earned',
      'active_days',
      'first_block',
      'last_block',
      'rank',
    ],
  },
  {
    name: 'leaderboard_by_group',
    columns: [
      'group_id',
      'account_id',
      'post_count',
      'reply_count',
      'reactions_received',
      'avg_reactions',
      'active_days',
      'rank',
    ],
  },
  {
    name: 'app_reputation',
    columns: [
      'app_id',
      'total_users',
      'total_rewarded',
      'total_actions',
      'active_days',
      'returning_users',
      'avg_user_reputation',
      'rank',
    ],
  },
];

/** Tracked Postgres query functions (Hasura `pg_track_function`). */
export const PUBLIC_FUNCTIONS = ['feed_pulse'] as const;

export const ADMIN_ONLY_TABLES = [
  'api_keys',
  'api_usage',
  'developer_subscriptions',
  'developer_apps',
  'app_notification_events',
  'developer_notification_rules',
  'notifications',
  'notification_webhook_endpoints',
  'notification_delivery_attempts',
  'notification_counts',
  'notification_cursors',
  'push_subscriptions',
  'user_mutes',
];

export const INTENTIONALLY_UNEXPOSED_RELATIONS = [
  'leaderboard_agent_features',
  'leaderboard_snapshots',
  'reward_weights',
  // Reputation helpers (joined into reputation_scores; not public GraphQL).
  'paid_support_inbound_events',
  'author_amplify_received',
];
