export interface HasuraTableDefinition {
  name: string;
  columns: string[];
}

export const PUBLIC_TABLES: HasuraTableDefinition[] = [
  {
    name: 'data_updates',
    columns: [
      'id',
      'block_height',
      'block_timestamp',
      'receipt_id',
      'operation',
      'author',
      'partition_id',
      'path',
      'value',
      'account_id',
      'data_type',
      'data_id',
      'group_id',
      'group_path',
      'is_group_content',
      'target_account',
      'parent_path',
      'parent_author',
      'parent_type',
      'ref_path',
      'ref_author',
      'ref_type',
      'refs',
      'ref_authors',
      'derived_id',
      'derived_type',
      'writes',
      'extra_data',
    ],
  },
  {
    name: 'storage_updates',
    columns: [
      'id',
      'block_height',
      'block_timestamp',
      'receipt_id',
      'operation',
      'author',
      'partition_id',
      'amount',
      'previous_balance',
      'new_balance',
      'pool_id',
      'pool_key',
      'group_id',
      'reason',
      'auth_type',
      'actor_id',
      'payer_id',
      'target_id',
      'available_balance',
      'donor',
      'payer',
      'previous_pool_balance',
      'new_pool_balance',
      'bytes',
      'remaining_allowance',
      'pool_account',
      'max_bytes',
      'new_shared_bytes',
      'new_used_bytes',
      'pool_available_bytes',
      'used_bytes',
      'extra_data',
    ],
  },
  {
    name: 'group_updates',
    columns: [
      'id',
      'block_height',
      'block_timestamp',
      'receipt_id',
      'operation',
      'author',
      'partition_id',
      'group_id',
      'member_id',
      'member_nonce',
      'member_nonce_path',
      'role',
      'level',
      'path',
      'value',
      'pool_key',
      'amount',
      'previous_pool_balance',
      'new_pool_balance',
      'quota_bytes',
      'quota_used',
      'daily_limit',
      'previously_enabled',
      'proposal_id',
      'proposal_type',
      'status',
      'sequence_number',
      'title',
      'description',
      'auto_vote',
      'created_at',
      'locked_member_count',
      'locked_deposit',
      'expires_at',
      'tally_path',
      'counter_path',
      'voter',
      'approve',
      'total_votes',
      'yes_votes',
      'no_votes',
      'should_execute',
      'should_reject',
      'voted_at',
      'voting_period',
      'participation_quorum',
      'approval_threshold',
      'permission_key',
      'permission_value',
      'permission_target',
      'name',
      'is_public',
      'creator_role',
      'storage_allocation',
      'extra_data',
    ],
  },
  {
    name: 'permission_updates',
    columns: [
      'id',
      'block_height',
      'block_timestamp',
      'receipt_id',
      'operation',
      'author',
      'partition_id',
      'path',
      'target_id',
      'public_key',
      'level',
      'expires_at',
      'value',
      'deleted',
      'derived_id',
      'derived_type',
      'permission_nonce',
    ],
  },
  {
    name: 'contract_updates',
    columns: [
      'id',
      'block_height',
      'block_timestamp',
      'receipt_id',
      'operation',
      'author',
      'partition_id',
      'path',
      'derived_id',
      'derived_type',
      'target_id',
      'auth_type',
      'actor_id',
      'payer_id',
      'extra_data',
    ],
  },
  {
    name: 'profiles_current',
    columns: [
      'account_id',
      'field',
      'value',
      'block_height',
      'block_timestamp',
      'operation',
    ],
  },
  {
    name: 'posts_current',
    columns: [
      'account_id',
      'post_id',
      'value',
      'block_height',
      'block_timestamp',
      'receipt_id',
      'parent_path',
      'parent_author',
      'parent_type',
      'ref_path',
      'ref_author',
      'ref_type',
      'group_id',
      'is_group_content',
    ],
  },
  {
    name: 'standings_current',
    columns: [
      'account_id',
      'target_account',
      'value',
      'block_height',
      'block_timestamp',
    ],
  },
  {
    name: 'reactions_current',
    columns: [
      'account_id',
      'post_owner',
      'path',
      'value',
      'block_height',
      'block_timestamp',
      'operation',
    ],
  },
  {
    name: 'reaction_counts',
    columns: [
      'post_owner',
      'post_path',
      'reaction_count',
      'last_reaction_block',
    ],
  },
  {
    name: 'standing_counts',
    columns: ['account_id', 'standing_with_count', 'last_standing_block'],
  },
  {
    name: 'standing_out_counts',
    columns: [
      'account_id',
      'standing_with_others_count',
      'last_standing_block',
    ],
  },
  {
    name: 'thread_replies',
    columns: [
      'reply_author',
      'reply_id',
      'parent_author',
      'parent_path',
      'parent_type',
      'value',
      'block_height',
      'block_timestamp',
      'group_id',
    ],
  },
  {
    name: 'quotes',
    columns: [
      'quote_author',
      'quote_id',
      'ref_author',
      'ref_path',
      'ref_type',
      'value',
      'block_height',
      'block_timestamp',
      'group_id',
    ],
  },
  {
    name: 'edges_current',
    columns: [
      'source',
      'target',
      'edge_type',
      'value',
      'block_height',
      'block_timestamp',
      'operation',
      'group_id',
    ],
  },
  {
    name: 'edge_counts',
    columns: ['account_id', 'edge_type', 'inbound_count', 'last_block'],
  },
  {
    name: 'token_events',
    columns: [
      'id',
      'block_height',
      'block_timestamp',
      'receipt_id',
      'event_type',
      'owner_id',
      'amount',
      'memo',
      'old_owner_id',
      'new_owner_id',
      'extra_data',
    ],
  },
  {
    name: 'token_balances',
    columns: [
      'account_id',
      'last_event_type',
      'last_event_block',
      'updated_at',
    ],
  },
  {
    name: 'boost_events',
    columns: [
      'id',
      'block_height',
      'block_timestamp',
      'receipt_id',
      'account_id',
      'event_type',
      'success',
      'amount',
      'effective_boost',
      'months',
      'new_months',
      'new_effective_boost',
      'elapsed_ns',
      'total_released',
      'remaining_pool',
      'infra_share',
      'rewards_share',
      'total_pool',
      'receiver_id',
      'old_owner',
      'new_owner',
      'old_version',
      'new_version',
      'deposit',
      'extra_data',
    ],
  },
  {
    name: 'booster_state',
    columns: [
      'account_id',
      'locked_amount',
      'effective_boost',
      'lock_months',
      'total_claimed',
      'total_credits_purchased',
      'last_event_type',
      'last_event_block',
      'updated_at',
    ],
  },
  {
    name: 'boost_credit_purchases',
    columns: [
      'id',
      'block_height',
      'block_timestamp',
      'receipt_id',
      'account_id',
      'amount',
      'infra_share',
      'rewards_share',
    ],
  },
  {
    name: 'rewards_events',
    columns: [
      'id',
      'block_height',
      'block_timestamp',
      'receipt_id',
      'account_id',
      'event_type',
      'success',
      'amount',
      'source',
      'credited_by',
      'app_id',
      'new_balance',
      'old_owner',
      'new_owner',
      'old_max',
      'new_max',
      'executor',
      'caller',
      'old_version',
      'new_version',
      'extra_data',
    ],
  },
  {
    name: 'user_reward_state',
    columns: [
      'account_id',
      'total_earned',
      'total_claimed',
      'last_credit_block',
      'last_claim_block',
      'updated_at',
    ],
  },
  {
    name: 'scarces_events',
    columns: [
      'id',
      'block_height',
      'block_timestamp',
      'receipt_id',
      'event_type',
      'operation',
      'author',
      'token_id',
      'collection_id',
      'listing_id',
      'owner_id',
      'creator_id',
      'buyer_id',
      'seller_id',
      'bidder',
      'winner_id',
      'sender_id',
      'receiver_id',
      'account_id',
      'executor',
      'contract_id',
      'scarce_contract_id',
      'amount',
      'price',
      'old_price',
      'new_price',
      'bid_amount',
      'attempted_price',
      'marketplace_fee',
      'app_pool_amount',
      'app_commission',
      'creator_payment',
      'revenue',
      'new_balance',
      'initial_balance',
      'refunded_amount',
      'refund_per_token',
      'refund_pool',
      'quantity',
      'total_supply',
      'redeem_count',
      'max_redeems',
      'bid_count',
      'refundable_count',
      'reserve_price',
      'buy_now_price',
      'min_bid_increment',
      'winning_bid',
      'expires_at',
      'auction_duration_ns',
      'anti_snipe_extension_ns',
      'app_id',
      'funder',
      'old_owner',
      'new_owner',
      'old_recipient',
      'new_recipient',
      'reason',
      'mode',
      'memo',
      'token_ids',
      'prices',
      'receivers',
      'accounts',
      'old_version',
      'new_version',
      'total_fee_bps',
      'app_pool_fee_bps',
      'platform_storage_fee_bps',
      'start_time',
      'end_time',
      'new_expires_at',
      'old_expires_at',
      'approval_id',
      'deposit',
      'remaining_balance',
      'cap',
      'extra_data',
    ],
  },
  {
    name: 'leaderboard_boost',
    columns: [
      'account_id',
      'locked_amount',
      'effective_boost',
      'lock_months',
      'total_claimed',
      'total_credits_purchased',
      'last_event_block',
      'rank',
    ],
  },
  {
    name: 'leaderboard_rewards',
    columns: [
      'account_id',
      'total_earned',
      'total_claimed',
      'unclaimed',
      'credit_count',
      'last_credit_block',
      'last_claim_block',
      'rank',
    ],
  },
  {
    name: 'reward_activity_daily',
    columns: [
      'account_id',
      'activity_date',
      'credit_count',
      'total_amount',
      'last_block',
    ],
  },
  {
    name: 'content_activity',
    columns: [
      'account_id',
      'total_posts',
      'reply_count',
      'quote_count',
      'group_posts',
      'total_reactions_received',
      'avg_reactions_per_post',
      'active_days',
      'unique_reply_targets',
      'last_post_block',
    ],
  },
  {
    name: 'scarces_activity',
    columns: [
      'account_id',
      'items_created',
      'items_sold',
      'revenue_earned',
      'items_purchased',
      'amount_spent',
      'collections_created',
      'last_scarces_block',
    ],
  },
  {
    name: 'reputation_scores',
    columns: [
      'account_id',
      'standing_with',
      'standing_out',
      'boost',
      'lock_months',
      'rewards_earned',
      'total_posts',
      'reply_count',
      'reactions_received',
      'avg_reactions',
      'active_days',
      'unique_conversations',
      'scarces_created',
      'scarces_sold',
      'scarces_revenue_near',
      'social_score',
      'commitment_score',
      'quality_score',
      'consistency_score',
      'scarces_score',
      'reputation',
      'rank',
    ],
  },
  {
    name: 'leaderboard_by_app',
    columns: [
      'app_id',
      'account_id',
      'action_count',
      'total_earned',
      'active_days',
      'first_block',
      'last_block',
      'rank',
    ],
  },
  {
    name: 'leaderboard_by_group',
    columns: [
      'group_id',
      'account_id',
      'post_count',
      'reply_count',
      'reactions_received',
      'avg_reactions',
      'active_days',
      'rank',
    ],
  },
  {
    name: 'app_reputation',
    columns: [
      'app_id',
      'total_users',
      'total_rewarded',
      'total_actions',
      'active_days',
      'returning_users',
      'avg_user_reputation',
      'rank',
    ],
  },
];

export const ADMIN_ONLY_TABLES = [
  'api_keys',
  'api_usage',
  'developer_subscriptions',
  'developer_apps',
  'app_notification_events',
  'developer_notification_rules',
  'notifications',
  'notification_webhook_endpoints',
  'notification_delivery_attempts',
  'notification_counts',
  'notification_cursors',
];

export const INTENTIONALLY_UNEXPOSED_RELATIONS = [
  'leaderboard_snapshots',
  'reward_weights',
];
