export const TX_TOAST_EYEBROW = {
  wallet: 'Wallet',
  confirming: 'Confirming',
} as const;

/** Chain-confirmation lines — shown in toast after wallet submit. */
export const txToastConfirming = {
  collectingSocial: 'Confirming collection…',
  addingStorage: 'Confirming storage…',
  withdrawingStorage: 'Confirming withdrawal…',
  fundingSharePool: 'Confirming funding…',
  sharingStorage: 'Confirming share…',
  creatingGuild: 'Confirming guild…',
  joiningGuild: 'Confirming join…',
  requestingGuildAccess: 'Confirming request…',
  cancelingGuildRequest: 'Confirming cancel…',
  leavingGuild: 'Confirming leave…',
  posting: 'Confirming post…',
  quoting: 'Confirming quote…',
  postingToGuild: 'Confirming post…',
  quotingGuildPost: 'Confirming quote…',
  savingGuildSettings: 'Confirming save…',
  proposingGuildUpdate: 'Confirming proposal…',
  reviewingGuildRequest: 'Confirming review…',
  votingGuildProposal: 'Confirming vote…',
  addingGuildMember: 'Confirming add…',
  updatingGuildMemberRole: 'Confirming update…',
  removingGuildMember: 'Confirming removal…',
  transferringGuildOwnership: 'Confirming transfer…',
  grantingGuildSpaceWriter: 'Confirming access…',
  proposingGuildSpaceWriter: 'Confirming proposal…',
  revokingGuildSpaceWriter: 'Confirming removal…',
  proposingGuildSpaceWriterRevoke: 'Confirming proposal…',
  amplifyingPost: 'Confirming amplify…',
  listingScarce: 'Confirming listing…',
  sellingScarce: 'Confirming listing…',
  buyingScarce: 'Confirming purchase…',
  biddingScarce: 'Confirming bid…',
  buyingScarceNow: 'Confirming buy now…',
  settlingScarceAuction: 'Confirming settle…',
  makingScarceOffer: 'Confirming offer…',
  acceptingScarceOffer: 'Confirming accept…',
  cancelingScarceOffer: 'Confirming cancel…',
  cancelingScarceListing: 'Confirming cancel…',
  creatingCollection: 'Starting your drop…',
  mintingCollection: 'Minting…',
  pausingCollection: 'Pausing drop…',
  resumingCollection: 'Resuming drop…',
  deletingCollection: 'Deleting drop…',
  updatingAllowlist: 'Updating allowlist…',
  savingSeries: 'Saving series…',
  creatingApp: 'Opening your hub…',
  updatingApp: 'Saving hub settings…',
  updatingAppCreators: 'Updating creators…',
  transferringAppOwnership: 'Transferring hub…',
  requestingStoreAccess: 'Requesting publishing access…',
  withdrawingStoreAccess: 'Withdrawing request…',
  decliningStoreAccess: 'Declining request…',
  committingBoost: 'Confirming boost…',
  collectingBoost: 'Confirming collection…',
  renewingBoost: 'Confirming renewal…',
  extendingBoost: 'Confirming extension…',
  releasingBoost: 'Confirming release…',
  blockingAccount: 'Confirming block…',
  unblockingAccount: 'Confirming unblock…',
} as const;

export const txToastPending = {
  collectingSocial: 'Collecting SOCIAL…',
  addingStorage: 'Adding storage…',
  withdrawingStorage: 'Withdrawing storage…',
  fundingSharePool: 'Funding share pool…',
  sharingStorage: 'Sharing storage…',
  creatingGuild: 'Creating guild…',
  joiningGuild: 'Joining guild…',
  requestingGuildAccess: 'Requesting access…',
  cancelingGuildRequest: 'Canceling request…',
  leavingGuild: 'Leaving guild…',
  posting: 'Posting…',
  quoting: 'Quoting…',
  postingToGuild: 'Posting to guild…',
  quotingGuildPost: 'Quoting…',
  savingGuildSettings: 'Saving guild…',
  proposingGuildUpdate: 'Submitting proposal…',
  reviewingGuildRequest: 'Reviewing request…',
  votingGuildProposal: 'Submitting vote…',
  addingGuildMember: 'Adding member…',
  updatingGuildMemberRole: 'Updating role…',
  removingGuildMember: 'Removing member…',
  transferringGuildOwnership: 'Transferring ownership…',
  grantingGuildSpaceWriter: 'Allowing to share…',
  proposingGuildSpaceWriter: 'Proposing access…',
  revokingGuildSpaceWriter: 'Removing access…',
  proposingGuildSpaceWriterRevoke: 'Proposing removal…',
  amplifyingPost: 'Amplifying…',
  listingScarce: 'Listing…',
  sellingScarce: 'Listing for sale…',
  buyingScarce: 'Buying scarce…',
  biddingScarce: 'Placing bid…',
  buyingScarceNow: 'Buying now…',
  settlingScarceAuction: 'Settling auction…',
  makingScarceOffer: 'Making offer…',
  acceptingScarceOffer: 'Accepting offer…',
  cancelingScarceOffer: 'Canceling offer…',
  cancelingScarceListing: 'Canceling listing…',
  blockingAccount: 'Blocking…',
  unblockingAccount: 'Unblocking…',
} as const;

export const txToastSuccess = {
  socialCollected: 'SOCIAL collected.',
  rewardsCollected: (amountLabel: string) => `${amountLabel} SOCIAL collected.`,
  rewardCredited: (amountLabel: string, reason?: string | null) =>
    reason?.trim()
      ? `+${amountLabel} SOCIAL · ${reason.trim()}`
      : `+${amountLabel} SOCIAL`,
  profileSaved: 'Profile saved.',
  moodSaved: 'Mood saved.',
  pageLookSaved: 'Page look saved.',
  storageAdded: 'Storage added.',
  storageWithdrawn: 'Storage withdrawn to wallet.',
  sharePoolFunded: 'Share pool funded.',
  storageShared: 'Storage shared.',
  guildCreated: 'Guild created.',
  guildJoined: 'Guild joined.',
  guildAccessRequested: 'Access requested.',
  guildRequestCanceled: 'Request canceled.',
  guildLeft: 'Guild left.',
  postPublished: 'Posted.',
  replyPublished: 'Reply posted.',
  quotePublished: 'Quote posted.',
  guildPostPublished: 'Posted to guild.',
  guildQuotePublished: 'Quote posted.',
  guildSettingsSaved: 'Guild updated.',
  guildUpdateProposed: 'Update proposed.',
  guildRequestApproved: 'Request approved.',
  guildRequestDenied: 'Request denied.',
  guildVoteRecorded: 'Vote recorded.',
  guildMemberAdded: 'Member added.',
  guildMemberRoleUpdated: 'Member role updated.',
  guildMemberRemoved: 'Member removed.',
  guildOwnershipTransferred: 'Ownership transferred.',
  guildSpaceWriterGranted: 'Can share in room.',
  guildSpaceWriterProposed: 'Access proposed.',
  guildSpaceWriterRevoked: 'Sharing removed.',
  guildSpaceWriterRevokeProposed: 'Removal proposed.',
  endorsementSaved: (name: string) => `Endorsed ${name}.`,
  supportSent: (name: string) => `Supported ${name}.`,
  supportCollected: 'Support SOCIAL collected.',
  postAmplified: 'Post amplified.',
  scarceListed: 'Listed.',
  scarceSoldListed: 'Listed for sale.',
  scarcePurchased: 'Scarce collected.',
  scarceBidPlaced: 'Bid placed.',
  scarceBoughtNow: 'You won — scarce is yours.',
  scarceAuctionSettled: 'Auction settled.',
  scarceAuctionCollected: 'Scarce collected.',
  scarceOfferMade: 'Offer made.',
  scarceOfferAccepted: 'Offer accepted.',
  scarceOfferCanceled: 'Offer canceled.',
  scarceListingCanceled: 'Listing canceled.',
  scarceAuctionListed: 'Auction listed.',
  collectionCreated: 'Drop is live.',
  collectionMinted: 'Minted from the drop.',
  collectionPaused: 'Drop paused.',
  collectionResumed: 'Drop is live again.',
  collectionDeleted: 'Drop deleted.',
  allowlistUpdated: 'Allowlist updated.',
  seriesSaved: 'Series updated.',
  appCreated: 'Your hub is open.',
  appUpdated: 'Hub settings saved.',
  appCreatorsUpdated: 'Creators updated.',
  appOwnershipTransferred: 'Hub ownership transferred.',
  storeAccessRequested: 'Publishing access requested.',
  storeAccessWithdrawn: 'Request withdrawn.',
  storeAccessDeclined: 'Request declined.',
  boostCommitted: (amountLabel: string) => `${amountLabel} SOCIAL committed.`,
  boostCollected: 'SOCIAL collected.',
  boostRenewed: 'Commitment renewed.',
  boostExtended: (periodLabel: string) => `Extended to ${periodLabel}.`,
  boostReleased: 'Position released. SOCIAL collected.',
  accountBlocked: 'Account blocked.',
  accountUnblocked: 'Account unblocked.',
  accountMuted: 'Account muted.',
  accountUnmuted: 'Account unmuted.',
} as const;

export const txToastError = {
  collectSocialFailed: 'Could not collect SOCIAL.',
  profileSaveFailed: 'Could not save profile.',
  moodSaveFailed: 'Could not save mood.',
  pageLookSaveFailed: 'Could not save page look.',
  storageDepositFailed: 'Could not add storage.',
  storageWithdrawFailed: 'Could not withdraw storage.',
  sharePoolFundFailed: 'Could not fund share pool.',
  storageShareFailed: 'Could not share storage.',
  guildCreateFailed: 'Could not create guild.',
  guildMembershipFailed: 'Could not update guild membership.',
  postFailed: 'Could not publish post.',
  replyFailed: 'Could not post reply.',
  quoteFailed: 'Could not post quote.',
  guildPostFailed: 'Could not post to guild.',
  guildQuoteFailed: 'Could not post quote.',
  guildSettingsFailed: 'Could not save guild settings.',
  guildRequestReviewFailed: 'Could not review request.',
  guildVoteFailed: 'Could not submit vote.',
  guildAddMemberFailed: 'Could not add member.',
  guildMemberRoleFailed: 'Could not update member role.',
  guildRemoveMemberFailed: 'Could not remove member.',
  guildOwnershipTransferFailed: 'Could not transfer ownership.',
  guildSpaceWriterFailed: 'Could not update who can share.',
  endorsementFailed: 'Could not save endorsement.',
  supportFailed: 'Could not send support.',
  claimSupportFailed: 'Could not claim support.',
  amplifyFailed: 'Could not amplify post.',
  listScarceFailed: 'Could not list scarce.',
  sellScarceFailed: 'Could not list scarce for sale.',
  buyScarceFailed: 'Could not buy scarce.',
  bidScarceFailed: 'Could not place bid.',
  buyScarceNowFailed: 'Could not buy now.',
  settleScarceAuctionFailed: 'Could not settle auction.',
  makeScarceOfferFailed: 'Could not make offer.',
  acceptScarceOfferFailed: 'Could not accept offer.',
  cancelScarceOfferFailed: 'Could not cancel offer.',
  cancelScarceListingFailed: 'Could not cancel listing.',
  listScarceAuctionFailed: 'Could not list auction.',
  createCollectionFailed: 'Could not start the drop.',
  mintCollectionFailed: 'Could not mint from the drop.',
  pauseCollectionFailed: 'Could not pause the drop.',
  resumeCollectionFailed: 'Could not resume the drop.',
  deleteCollectionFailed: 'Could not delete the drop.',
  variationSetSize: (min: number, max: string, count: string) =>
    `Sets hold ${min}–${max} images — this would be ${count}.`,
  variationSetPickRange: (min: number, max: string) =>
    `Pick ${min}–${max} images — one per piece.`,
  variationImageType: 'Use JPG, PNG, or WebP images.',
  variationFormatMismatch: 'All set images must share one format.',
  variationImageTooLarge: 'Each image must be 5 MB or smaller.',
  variationSetTooLarge: (mb: number) =>
    `The whole set must stay under ${mb} MB — try smaller files.`,
  loveTrackFailed: 'Could not love this track.',
  loveDropFailed: 'Could not love this drop.',
  offlineCacheFailed: 'Could not keep this offline.',
  offlineRemoveFailed: 'Could not remove the offline copy.',
  updateAllowlistFailed: 'Could not update the allowlist.',
  saveSeriesFailed: 'Could not save the series.',
  createAppFailed: 'Could not open the hub.',
  updateAppFailed: 'Could not save hub settings.',
  updateAppCreatorsFailed: 'Could not update creators.',
  transferAppOwnershipFailed: 'Could not transfer the hub.',
  requestStoreAccessFailed: 'Could not request publishing access.',
  withdrawStoreAccessFailed: 'Could not withdraw the request.',
  declineStoreAccessFailed: 'Could not decline the request.',
  commitBoostFailed: 'Could not commit SOCIAL.',
  collectBoostFailed: 'Could not collect boost rewards.',
  renewBoostFailed: 'Could not renew the commitment.',
  extendBoostFailed: 'Could not extend the commitment.',
  releaseBoostFailed: 'Could not release the position.',
  blockAccountFailed: 'Could not block account.',
  unblockAccountFailed: 'Could not unblock account.',
  muteAccountFailed: 'Could not mute account.',
  unmuteAccountFailed: 'Could not unmute account.',
} as const;

/** Governance / partners — formal one-liners for DAO act_proposal flows. */
export const txToastGovPending = {
  actionSubmitted: (actionLabel: string) => `${actionLabel} submitted…`,
} as const;

export const txToastGovSuccess = {
  actionConfirmed: (actionLabel: string) => `${actionLabel} confirmed.`,
} as const;

export const txToastGovError = {
  actionFailed: (actionLabel: string) => `${actionLabel} failed.`,
} as const;
