/**
 * Compose routes: Token lifecycle — transfer, burn, renew, redeem, revoke, refund.
 *
 * Each action has a relay endpoint (POST /compose/xxx) and a prepare endpoint
 * (POST /compose/prepare/xxx) generated by the actionHandlers factory.
 */

import { Router } from 'express';
import { actionHandlers } from './helpers.js';
import {
  buildTransferAction,
  buildBatchTransferAction,
  buildBurnAction,
  buildRenewTokenAction,
  buildRedeemTokenAction,
  buildRevokeTokenAction,
  buildClaimRefundAction,
} from '../../services/compose/token.js';

export const tokenRouter = Router();

// ── Transfer ────────────────────────────────────────────────────────────────
const transfer = actionHandlers(
  (b) =>
    buildTransferAction({
      tokenId: String(b.tokenId || ''),
      receiverId: String(b.receiverId || ''),
      memo: b.memo ? String(b.memo) : undefined,
      targetAccount: b.targetAccount ? String(b.targetAccount) : undefined,
    }),
  'transfer'
);
tokenRouter.post('/transfer', transfer.relay);
tokenRouter.post('/prepare/transfer', transfer.prepare);

// ── Batch Transfer ──────────────────────────────────────────────────────────
const batchTransfer = actionHandlers(
  (b) =>
    buildBatchTransferAction({
      transfers: b.transfers as Array<{
        receiver_id: string;
        token_id: string;
        memo?: string;
      }>,
      targetAccount: b.targetAccount ? String(b.targetAccount) : undefined,
    }),
  'batch-transfer'
);
tokenRouter.post('/batch-transfer', batchTransfer.relay);
tokenRouter.post('/prepare/batch-transfer', batchTransfer.prepare);

// ── Burn ────────────────────────────────────────────────────────────────────
const burn = actionHandlers(
  (b) =>
    buildBurnAction({
      tokenId: String(b.tokenId || ''),
      collectionId: b.collectionId ? String(b.collectionId) : undefined,
      targetAccount: b.targetAccount ? String(b.targetAccount) : undefined,
    }),
  'burn'
);
tokenRouter.post('/burn', burn.relay);
tokenRouter.post('/prepare/burn', burn.prepare);

// ── Renew Token ─────────────────────────────────────────────────────────────
const renew = actionHandlers(
  (b) =>
    buildRenewTokenAction({
      tokenId: String(b.tokenId || ''),
      collectionId: String(b.collectionId || ''),
      newExpiresAt: Number(b.newExpiresAt),
      targetAccount: b.targetAccount ? String(b.targetAccount) : undefined,
    }),
  'renew-token'
);
tokenRouter.post('/renew-token', renew.relay);
tokenRouter.post('/prepare/renew-token', renew.prepare);

// ── Redeem Token ────────────────────────────────────────────────────────────
const redeem = actionHandlers(
  (b) =>
    buildRedeemTokenAction({
      tokenId: String(b.tokenId || ''),
      collectionId: String(b.collectionId || ''),
      targetAccount: b.targetAccount ? String(b.targetAccount) : undefined,
    }),
  'redeem-token'
);
tokenRouter.post('/redeem-token', redeem.relay);
tokenRouter.post('/prepare/redeem-token', redeem.prepare);

// ── Revoke Token ────────────────────────────────────────────────────────────
const revokeToken = actionHandlers(
  (b) =>
    buildRevokeTokenAction({
      tokenId: String(b.tokenId || ''),
      collectionId: String(b.collectionId || ''),
      memo: b.memo ? String(b.memo) : undefined,
      targetAccount: b.targetAccount ? String(b.targetAccount) : undefined,
    }),
  'revoke-token'
);
tokenRouter.post('/revoke-token', revokeToken.relay);
tokenRouter.post('/prepare/revoke-token', revokeToken.prepare);

// ── Claim Refund ────────────────────────────────────────────────────────────
const claimRefund = actionHandlers(
  (b) =>
    buildClaimRefundAction({
      tokenId: String(b.tokenId || ''),
      collectionId: String(b.collectionId || ''),
      targetAccount: b.targetAccount ? String(b.targetAccount) : undefined,
    }),
  'claim-refund'
);
tokenRouter.post('/claim-refund', claimRefund.relay);
tokenRouter.post('/prepare/claim-refund', claimRefund.prepare);
