// This file is @generated by prost-build.
/// Top-level output containing all decoded events from a block
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag = "1")]
    pub events: ::prost::alloc::vec::Vec<Event>,
    #[prost(uint64, tag = "2")]
    pub block_height: u64,
    #[prost(uint64, tag = "3")]
    pub block_timestamp: u64,
    #[prost(string, tag = "4")]
    pub block_hash: ::prost::alloc::string::String,
}
/// Decoded OnSocial event from contract logs
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Event {
    /// Event metadata
    ///
    /// e.g., "onsocial"
    #[prost(string, tag = "1")]
    pub evt_standard: ::prost::alloc::string::String,
    /// e.g., "1.0.0"
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    /// e.g., "user", "post", "comment"
    #[prost(string, tag = "3")]
    pub evt_type: ::prost::alloc::string::String,
    /// e.g., "set", "delete"
    #[prost(string, tag = "4")]
    pub op_type: ::prost::alloc::string::String,
    /// Event data (optional - may be null)
    #[prost(message, optional, tag = "5")]
    pub data: ::core::option::Option<EventData>,
    /// NEAR receipt info for tracing
    #[prost(string, tag = "6")]
    pub receipt_id: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub predecessor_id: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub receiver_id: ::prost::alloc::string::String,
}
/// Core event data structure (matches BaseEventData in Rust)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventData {
    #[prost(uint64, tag = "1")]
    pub block_height: u64,
    #[prost(uint64, tag = "2")]
    pub timestamp: u64,
    #[prost(string, tag = "3")]
    pub author: ::prost::alloc::string::String,
    /// Partition ID for indexer routing (0 if not set)
    #[prost(uint32, tag = "4")]
    pub partition_id: u32,
    #[prost(bool, tag = "5")]
    pub has_partition_id: bool,
    /// Extra key-value pairs from the event
    #[prost(message, repeated, tag = "6")]
    pub extra: ::prost::alloc::vec::Vec<ExtraField>,
    /// Substreams-compatible fields
    #[prost(string, tag = "7")]
    pub evt_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "8")]
    pub log_index: u32,
}
/// Extra field from event (matches BorshExtra in Rust)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExtraField {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub value: ::core::option::Option<ExtraValue>,
}
/// Value types (matches BorshValue enum in Rust)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExtraValue {
    #[prost(oneof = "extra_value::Value", tags = "1, 2, 3, 4")]
    pub value: ::core::option::Option<extra_value::Value>,
}
/// Nested message and enum types in `ExtraValue`.
pub mod extra_value {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(string, tag = "1")]
        StringValue(::prost::alloc::string::String),
        /// Numbers stored as strings for precision
        #[prost(string, tag = "2")]
        NumberValue(::prost::alloc::string::String),
        #[prost(bool, tag = "3")]
        BoolValue(bool),
        /// True if value is null
        #[prost(bool, tag = "4")]
        IsNull(bool),
    }
}
