# Use official Rust image as builder
FROM rust:latest AS builder

WORKDIR /usr/src/kms-backend
# Copy your backend source code into the container (adjust path as needed)
COPY ./kms-backend/ .

RUN cargo build --release

# Use a minimal base image for runtime
FROM debian:bookworm-slim AS runtime
WORKDIR /app
COPY --from=builder /usr/src/kms-backend/target/release/kms-backend .

CMD ["./kms-backend"]
