#!/bin/bash
# =============================================================================
# Generate .env.production LOCALLY (for debugging / dry-run only)
# =============================================================================
# Production deploys do NOT use this file. The deploy script pulls
# secrets directly from GSM on the server. This script is for:
#   - Previewing what .env.production would look like
#   - Local Docker Compose testing against testnet/mainnet
#
# Usage:
#   ./generate-env.sh testnet   # → deployment/.env.production (local only)
#   ./generate-env.sh mainnet

set -euo pipefail

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[0;33m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DEPLOY_DIR="$(cd "$SCRIPT_DIR/../deployment" && pwd)"
OUTPUT_FILE="$DEPLOY_DIR/.env.production"

NETWORK="${1:-}"

if [ -z "$NETWORK" ]; then
  echo "Usage: $0 <testnet|mainnet>"
  echo ""
  echo "Generates deployment/.env.production locally (preview / local Docker testing)"
  exit 1
fi

# --- Derive all network config from NETWORK (no extra files) ---
case "$NETWORK" in
  testnet)
    NEAR_SUFFIX="onsocial.testnet"
    PUBLIC_DOMAIN="testnet.onsocial.id"
    CORS_ORIGINS="https://testnet.onsocial.id,http://localhost:3000,http://localhost:4000"
    HASURA_CORS="https://testnet.onsocial.id,http://localhost:3000"
    KMS_KEYRING_0="relayer-keys-testnet"
    KMS_KEYRING_1="relayer-keys-inst-1"
    ;;
  mainnet)
    NEAR_SUFFIX="onsocial.near"
    PUBLIC_DOMAIN="api.onsocial.id"
    CORS_ORIGINS="https://onsocial.id,https://app.onsocial.id"
    HASURA_CORS="https://onsocial.id,https://app.onsocial.id"
    KMS_KEYRING_0="relayer-keys-mainnet"
    KMS_KEYRING_1="relayer-keys-mainnet-inst-1"
    ;;
  *)
    echo -e "${RED}❌ Unknown network: $NETWORK (expected testnet or mainnet)${NC}"
    exit 1
    ;;
esac

echo -e "${YELLOW}⚠️  This generates a LOCAL preview. Production deploys pull secrets on the server.${NC}"
echo ""

# Pull secrets from GSM
echo -e "Pulling secrets from Google Secret Manager..."
SECRETS=$("$SCRIPT_DIR/pull-secrets.sh" 2>/tmp/gsm-warnings.txt) || {
  echo -e "${RED}❌ Failed to pull secrets from GSM${NC}"
  echo "Make sure you're authenticated: gcloud auth login"
  echo "And secrets exist: scripts/setup-secrets.sh"
  exit 1
}

# Show any warnings (missing secrets)
if [ -s /tmp/gsm-warnings.txt ]; then
  echo -e "${YELLOW}$(cat /tmp/gsm-warnings.txt)${NC}"
fi

# Generate merged file
cat > "$OUTPUT_FILE" << EOF
# =============================================================================
# OnSocial Production Environment — ${NETWORK^^} (LOCAL PREVIEW)
# =============================================================================
# Generated by: scripts/generate-env.sh ${NETWORK}
# Generated at: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
#
# This is a LOCAL preview. Production deploys pull secrets directly
# from GSM on the server via: deployment/deploy-production.sh
# =============================================================================

# --- Network config (derived from NETWORK=${NETWORK}) ---
NEAR_NETWORK=${NETWORK}
RELAYER_ACCOUNT_ID=relayer.${NEAR_SUFFIX}
RELAYER_CONTRACT_ID=core.${NEAR_SUFFIX}
SOCIAL_TOKEN_CONTRACT=token.${NEAR_SUFFIX}
STAKING_CONTRACT=staking.${NEAR_SUFFIX}
MARKETPLACE_CONTRACT=marketplace.${NEAR_SUFFIX}
GCP_KMS_KEYRING_0=${KMS_KEYRING_0}
GCP_KMS_KEYRING_1=${KMS_KEYRING_1}
PUBLIC_DOMAIN=${PUBLIC_DOMAIN}
CORS_ORIGINS=${CORS_ORIGINS}
HASURA_GRAPHQL_CORS_DOMAIN=${HASURA_CORS}

EOF

echo "# --- Secrets (from Google Secret Manager) ---" >> "$OUTPUT_FILE"
echo "$SECRETS" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

echo -e "${GREEN}✅ Generated: $OUTPUT_FILE (local preview)${NC}"
echo -e "   Network:  ${NETWORK}"
echo ""
echo -e "${YELLOW}For production deployment, use:${NC}"
echo -e "   deployment/deploy-production.sh ${NETWORK} <server-ip>"
