import {
  ADMIN_WALLETS,
  CONTRACT_OWNER_WALLET,
  RELAYER_ACCOUNT,
} from '@/lib/portal-config';

export const CONTRACT_OWNER_WALLETS = [CONTRACT_OWNER_WALLET];

export { ADMIN_WALLETS, CONTRACT_OWNER_WALLET, RELAYER_ACCOUNT };
