version: '3'
services:
  relayer:
    build:
      context: .
      dockerfile: ../../docker/Dockerfile.relayer
    ports:
      - "3040:3030"
    volumes:
      - ./config.toml:/relayer-app/config.toml
      - ./account_keys:/relayer-app/account_keys
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
