ALTER TABLE partner_keys
  ADD COLUMN IF NOT EXISTS website_url TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS telegram_handle TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS x_handle TEXT NOT NULL DEFAULT '';